version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "CloudResume"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-16rl0i4odx6qh"
s3_prefix = "CloudResume"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
